"""Phase 3 comprehensive test — all evolution mechanisms."""
import asyncio, json, sys, shutil
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from agent.config import Config
from agent.engine import AgentEngine
from memory.neo4j_client import Neo4jClient
from memory.lifecycle import MemoryLifecycle
from memory.extractor import EntityExtractor
from skill_system.distillation import DistillationEngine
from skill_system.optimizer import SopOptimizer
from skill_system.compiler import SopCompiler
from skill_system.scorer import SkillScorer
from skill_system.registry import SkillRegistry
from tools.base import ToolCall

PASS = FAIL = 0

def check(name, cond, detail=""):
    global PASS, FAIL
    if cond: PASS += 1; print(f"  PASS: {name}")
    else: FAIL += 1; print(f"  FAIL: {name} -- {detail}")

# ====== Test DTO for fake LLM ======
from llm.base import LlmClient, LlmResponse, Message, ToolCall as LlmTC


class _FakeLLM(LlmClient):
    """Simulate LLM responses for testing."""
    def __init__(self):
        self.calls = []
        self.next_response = LlmResponse(content="{}")

    async def chat(self, messages, tools=None):
        self.calls.append(messages[0].content[:80] if messages else "")
        return self.next_response


async def test_1_entity_extractor():
    print("\n[1] LLM Entity Extractor")
    engine = AgentEngine(Config())
    await engine.init()

    llm = _FakeLLM()
    llm.next_response = LlmResponse(content=json.dumps({
        "entities": [
            {"entity_id": "ent_svc_db", "entity_type": "Service", "name": "PostgreSQL",
             "content": "Production database on 10.0.1.50:5432", "properties": {"host": "10.0.1.50", "port": 5432}},
            {"entity_id": "ent_person_alice", "entity_type": "Person", "name": "Alice",
             "content": "Database administrator", "properties": {"email": "alice@example.com"}},
        ],
        "relations": [
            {"from": "ent_person_alice", "type": "MANAGES", "to": "ent_svc_db"},
        ],
    }))

    # Create a completed distillation request
    await engine.neo4j.run("""CREATE (d:DistillationRequest {
        session_id: 'extract_test', reason: 'subgoal_completed',
        summary: 'Discovered PostgreSQL database at 10.0.1.50:5432 managed by Alice',
        status: 'completed', processed_at: datetime()})""")

    ex = EntityExtractor(engine.neo4j, llm)
    await ex.extract_recent(lookback_minutes=1440)

    # Verify entities created
    for eid in ["ent_svc_db", "ent_person_alice"]:
        r = await engine.neo4j.run(f"MATCH (e:Entity {{entity_id: '{eid}'}}) RETURN e")
        check(f"Entity {eid} created", len(r) > 0, f"found={len(r)}")

    # Verify relation
    r = await engine.neo4j.run(
        "MATCH (a:Entity {entity_id: 'ent_person_alice'})-[r:MANAGES]->(b:Entity {entity_id: 'ent_svc_db'}) RETURN r")
    check("Relation MANAGES created", len(r) > 0)

    check("LLM called", len(llm.calls) == 1, f"calls={len(llm.calls)}")

    # Cleanup
    await engine.neo4j.run("MATCH (d:DistillationRequest {session_id: 'extract_test'}) DETACH DELETE d")
    await engine.neo4j.run("MATCH (e:Entity) WHERE e.entity_id IN ['ent_svc_db', 'ent_person_alice'] DETACH DELETE e")
    await engine.close()


async def test_2_distillation_engine():
    print("\n[2] LLM Distillation Engine")
    engine = AgentEngine(Config())
    await engine.init()

    reg = SkillRegistry(engine.neo4j, engine.config.skills_dir)
    await reg.register("test-distill", "test", "Distillation test skill")

    llm = _FakeLLM()
    llm.next_response = LlmResponse(content="""---
name: test-distill
description: Test distillation SOP
category: test
stage: "SOP"
version: 1
---

# Test Distill
## Overview
Test SOP generated by distillation.
## When to Use
- When testing distillation
## Core Pattern
### Prerequisites
- Python 3.11+
### Steps
1. Run `echo hello`
2. Check output
## Common Mistakes
- Skipping step 1
""")

    # Create pending request
    await engine.neo4j.run("""CREATE (d:DistillationRequest {
        session_id: 'distill_test', reason: 'reusable_pattern',
        summary: 'Standard echo test procedure', status: 'pending', created_at: datetime()})""")

    de = DistillationEngine(engine.neo4j, llm)
    await de.process_pending()

    # Verify SKILL.md created
    p = Path(engine.config.skills_dir) / "test" / "test-distill" / "SKILL.md"
    check("SKILL.md generated", p.exists())
    if p.exists():
        content = p.read_text()
        check("SOP has steps", "Steps" in content, content[:100])

    check("LLM called", len(llm.calls) == 1)

    # Cleanup
    await engine.neo4j.run("MATCH (d:DistillationRequest {session_id: 'distill_test'}) DETACH DELETE d")
    await engine.neo4j.run("MATCH (s:Skill {skill_id: 'test/test-distill'}) DETACH DELETE s")
    await engine.neo4j.run("MATCH (c:SkillCategory {name: 'test'}) DETACH DELETE c")
    shutil.rmtree(Path(engine.config.skills_dir) / "test", ignore_errors=True)
    await engine.close()


async def test_3_sop_optimizer():
    print("\n[3] LLM SOP Optimizer")
    engine = AgentEngine(Config())
    await engine.init()

    reg = SkillRegistry(engine.neo4j, engine.config.skills_dir)
    await reg.register("test-opt", "test", "Optimization test")
    await reg.update_stage("test/test-opt", "SOP")

    # Write a SOP and usage data
    sop_dir = Path(engine.config.skills_dir) / "test" / "test-opt"
    sop_dir.mkdir(parents=True, exist_ok=True)
    (sop_dir / "SKILL.md").write_text("""---
name: test-opt
stage: "SOP"
---
# Test Opt
## Steps
1. Run file_read
2. Run code_run
""")

    # Create execution traces for the optimizer to analyze
    sid = 'opt-sess-2'
    await engine.neo4j.run(f"MERGE (s:Session {{session_id: '{sid}'}}) ON CREATE SET s.type='main', s.status='completed', s.created_at=datetime()")
    await engine.neo4j.run(f"MATCH (s:Session {{session_id: '{sid}'}}), (sk:Skill {{skill_id: 'test/test-opt'}}) MERGE (s)-[:USED_SKILL]->(sk)")
    await engine.neo4j.run(f"MATCH (s:Session {{session_id: '{sid}'}}) MERGE (s)-[:HAS_STEP]->(:ExecutionStep {{id: 'opt-step-0', name: 'file_read', role: 'system', step_index: 0, content: '[{{\"type\": \"tool_result\", \"name\": \"file_read\", \"output\": \"ok\"}}]', timestamp: datetime()}})")
    for i, tool in enumerate(["code_run", "memory_search"], start=1):
        await engine.neo4j.run(f"MATCH (prev:ExecutionStep {{id: 'opt-step-{i-1}'}}) MERGE (prev)-[:NEXT]->(:ExecutionStep {{id: 'opt-step-{i}', name: '{tool}', role: 'system', step_index: {i}, content: '[{{\"type\": \"tool_result\", \"name\": \"{tool}\", \"output\": \"ok\"}}]', timestamp: datetime()}})")


    llm = _FakeLLM()
    llm.next_response = LlmResponse(content=json.dumps({
        "suggestions": ["Add 'memory_search' step before file_read"],
        "variant_detected": True,
        "variant_description": "Some executions skip code_run and use web_scan instead",
        "recommended_updates": "Add conditional: if web data, use web_scan instead of file_read",
    }))

    opt = SopOptimizer(engine.neo4j, llm)
    result = await opt.optimize("test/test-opt")
    check("optimizer returns result", result is not None)
    if result:
        check("has suggestions", len(result["suggestions"]) > 0, str(result["suggestions"]))
        check("variant detected", result["variant_detected"])

    # Test heuristic fallback (no LLM)
    opt2 = SopOptimizer(engine.neo4j, None)
    result2 = await opt2.optimize("test/test-opt")
    check("heuristic fallback works", result2 is not None)

    # Cleanup
    await engine.neo4j.run("MATCH (s:Skill {skill_id: 'test/test-opt'}) DETACH DELETE s")
    await engine.neo4j.run("MATCH (s:Session {session_id: 'opt-sess-2'}) DETACH DELETE s")
    await engine.neo4j.run("MATCH (c:SkillCategory {name: 'test'}) DETACH DELETE c")
    shutil.rmtree(Path(engine.config.skills_dir) / "test", ignore_errors=True)
    await engine.close()


async def test_4_sop_compiler():
    print("\n[4] LLM SOP Compiler")
    engine = AgentEngine(Config())
    await engine.init()

    reg = SkillRegistry(engine.neo4j, engine.config.skills_dir)
    await reg.register("test-compile", "test", "Compile test")
    await reg.update_stage("test/test-compile", "SOP")

    # Write a SOP with mock data
    sop_dir = Path(engine.config.skills_dir) / "test" / "test-compile"
    (sop_dir / "SKILL.md").write_text("""---
name: test-compile
stage: "SOP"
---
# Test Compile
## Steps
1. Print hello
2. Print world
""")

    # Update skill to meet compile gates
    await engine.neo4j.run(
        "MATCH (s:Skill {skill_id: 'test/test-compile'}) SET s.confidence = 0.9, s.usage_count = 10")

    llm = _FakeLLM()
    llm.next_response = LlmResponse(content="""```python
print("hello")
print("world")
print("SOP execution complete.")
```
===TEST===
```python
import subprocess, sys
r = subprocess.run([sys.executable, 'main.py'], capture_output=True, text=True)
assert r.returncode == 0
assert 'SOP execution complete' in r.stdout
print('OK')
```""")

    comp = SopCompiler(engine.neo4j, llm, skills_dir=engine.config.skills_dir)
    result = await comp.compile_if_ready("test/test-compile")
    check("compiler returned", result is not None)
    if result:
        print(f"    Status: {result['status']}")
        check("compilation success", result["status"] in ("compiled", "failed_validation"),
              result.get("reason", result.get("output", "")[:80]))

    # Check scripts were written
    main_py = sop_dir / "scripts" / "main.py"
    check("main.py created", main_py.exists())
    if main_py.exists():
        check("main.py has content", 'print("hello")' in main_py.read_text())

    # Test gate: low confidence should skip
    await engine.neo4j.run(
        "MATCH (s:Skill {skill_id: 'test/test-compile'}) SET s.confidence = 0.5")
    result2 = await comp.compile_if_ready("test/test-compile")
    check("gate blocks low confidence", result2 and result2["status"] == "skipped",
          str(result2))

    # Cleanup
    await engine.neo4j.run("MATCH (s:Skill {skill_id: 'test/test-compile'}) DETACH DELETE s")
    await engine.neo4j.run("MATCH (c:SkillCategory {name: 'test'}) DETACH DELETE c")
    shutil.rmtree(Path(engine.config.skills_dir) / "test", ignore_errors=True)
    await engine.close()


async def test_5_four_d_scoring():
    print("\n[5] 4D Skill Scoring")
    engine = AgentEngine(Config())
    await engine.init()

    reg = SkillRegistry(engine.neo4j, engine.config.skills_dir)
    cats = ["web_automation", "data_processing", "web_automation", "ops", "web_automation"]
    for i, cat in enumerate(cats):
        await reg.register(f"score-s{i}", cat, f"Test skill {i}")
        # Vary usage
        await engine.neo4j.run(
            f"MATCH (s:Skill {{skill_id: '{cat}/score-s{i}'}}) SET s.usage_count = {i * 5}, s.activation = {1.0 - i * 0.1}")

    scorer = SkillScorer(engine.neo4j)
    results = await scorer.score_all()
    check("scoring produces results", len(results) >= 3, f"count={len(results)}")

    # Find top skill
    if results:
        top = results[0]
        check("score is positive", top["score"] > 0, str(top["score"]))
        check("has B/D/U/I dimensions", all(k in top["dimensions"] for k in ["B", "D", "U", "I"]),
              str(top["dimensions"]))
        print(f"    Top skill: {top['skill_id']} (score: {top['score']})")
        print(f"    Dimensions: {top['dimensions']}")

    # Weight adaptation
    if results:
        old_w = dict(scorer.weights)
        await scorer.adapt_weights({"score": 9.0, "dimensions": {"B": 8.0, "D": 2.0, "U": 1.0, "I": 0.0}}, actual_usage=0)
        check("weights changed", scorer.weights != old_w, f"{old_w} -> {scorer.weights}")

    # Cleanup
    for i, cat in enumerate(cats):
        await engine.neo4j.run(f"MATCH (s:Skill {{skill_id: '{cat}/score-s{i}'}}) DETACH DELETE s")
    for cat in set(cats):
        await engine.neo4j.run(f"MATCH (c:SkillCategory {{name: '{cat}'}}) DETACH DELETE c")
    await engine.close()


async def test_6_memory_lifecycle():
    print("\n[6] Memory Lifecycle")
    engine = AgentEngine(Config())
    await engine.init()

    lc = MemoryLifecycle(engine.neo4j)
    stats = await lc.get_stats()
    check("stats has skills", "skills" in stats, str(stats))
    check("stats has entities", "entities" in stats)
    check("stats has patterns", "patterns" in stats)

    # Create a test entity and test decay
    await engine.neo4j.run(
        """MERGE (e:Entity {entity_id: 'lifecycle-test'})
           SET e.entity_type = 'Test', e.name = 'LC', e.content = 'test',
               e.properties = '{}', e.activation = 0.5, e.source = 'test',
               e.created_at = datetime() - duration({days: 30})""")
    await lc.decay_all(days_threshold=7, rate=0.5)
    r = await engine.neo4j.run("MATCH (e:Entity {entity_id: 'lifecycle-test'}) RETURN e.activation AS a")
    check("entity decayed", r[0]["a"] < 0.5, f"activation={r[0]['a']}")

    await lc.consolidate_entity("lifecycle-test", boost=0.5)
    r = await engine.neo4j.run("MATCH (e:Entity {entity_id: 'lifecycle-test'}) RETURN e.activation AS a")
    check("entity consolidated", r[0]["a"] > 0.3, f"activation={r[0]['a']}")

    await engine.neo4j.run("MATCH (e:Entity {entity_id: 'lifecycle-test'}) DETACH DELETE e")
    await engine.close()


async def test_7_subconscious_loop():
    print("\n[7] Subconscious Loop")
    engine = AgentEngine(Config())
    await engine.init()

    from agent.subconscious import SubconsciousLoop
    check("subconscious created", engine._subconscious is not None)
    check("subconscious has LLM", engine._subconscious._llm is not None)

    # Test touch
    old_time = engine._subconscious._last_activity
    engine._subconscious.touch()
    check("touch updates activity", engine._subconscious._last_activity >= old_time)

    await engine.close()


async def test_8_skill_manage_new_actions():
    print("\n[8] skill_manage new actions")
    engine = AgentEngine(Config())
    await engine.init()

    reg = SkillRegistry(engine.neo4j, engine.config.skills_dir)
    await reg.register("test-actions", "test", "Action test")

    sm = engine.dispatcher._tools["skill_manage"]

    # Test score
    r = await sm.execute(ToolCall(id="t1", name="skill_manage",
        arguments={"action": "score", "skill_id": "test/test-actions"}))
    check("score action", r.success, r.output[:80])

    # Test distill (no pending requests)
    r = await sm.execute(ToolCall(id="t2", name="skill_manage",
        arguments={"action": "distill", "skill_id": "test/test-actions"}))
    check("distill action", r.success, r.output[:80])

    # Test optimize (no execution data)
    r = await sm.execute(ToolCall(id="t3", name="skill_manage",
        arguments={"action": "optimize", "skill_id": "test/test-actions"}))
    check("optimize action", r.success, r.output[:80])

    # Cleanup
    await engine.neo4j.run("MATCH (s:Skill {skill_id: 'test/test-actions'}) DETACH DELETE s")
    await engine.neo4j.run("MATCH (c:SkillCategory {name: 'test'}) DETACH DELETE c")
    await engine.close()


async def main():
    global PASS, FAIL
    print("=" * 50)
    print("  Phase 3 Comprehensive Test")
    print("=" * 50)

    await test_1_entity_extractor()
    await test_2_distillation_engine()
    await test_3_sop_optimizer()
    await test_4_sop_compiler()
    await test_5_four_d_scoring()
    await test_6_memory_lifecycle()
    await test_7_subconscious_loop()
    await test_8_skill_manage_new_actions()

    print("\n" + "=" * 50)
    print(f"  Results: {PASS} PASS, {FAIL} FAIL")
    print("=" * 50)
    return FAIL == 0


if __name__ == "__main__":
    sys.exit(0 if asyncio.run(main()) else 1)
